# -*- coding: utf-8 -*-
"""beginner_task_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19IFpVtOicPl2Po5ZzeuvOcqaJLCxWrq6

# Web Scraping Task - Extracting Product Data from BooksToScrape
# This script scrapes product names, prices, and ratings from a static e-commerce page
# and saves them into a CSV file for further analysis.
# Author: Saurabh Dabade
# Date: 19 February 2025
"""

import requests
from bs4 import BeautifulSoup
import csv

def scrape_books_page(url):
    # Send an HTTP GET request
    response = requests.get(url)

    # Check if request was successful
    if response.status_code != 200:
        print("Failed to retrieve the webpage")
        return []

    # Parse the HTML content
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find all book containers
    books = soup.find_all("article", class_="product_pod")

    # List to store extracted book data
    book_list = []

    for book in books:
        name = book.find("h3").find("a")["title"]
        price = book.find("p", class_="price_color").text.strip()

        # Extract rating
        rating_tag = book.find("p", class_="star-rating")
        rating = rating_tag["class"][1] if rating_tag else "No rating"

        book_list.append([name, price, rating])

    return book_list  # ✅ Return the data

if __name__ == "__main__":
    url = "http://books.toscrape.com/"
    book_list = scrape_books_page(url)  # ✅ Store the returned list

    # ✅ Ensure the list is not empty before writing to CSV
    if book_list:
        with open("products.csv", "w", newline="", encoding="utf-8-sig") as file:
            writer = csv.writer(file)
            writer.writerow(["Product Name", "Price", "Rating"])
            writer.writerows(book_list)

        print("Data has been successfully saved to products.csv")
    else:
        print("No data found. Check the scraping logic.")

import pandas as pd

# Read the CSV file
df = pd.read_csv("products.csv", encoding="utf-8-sig")

# Display the first 5 rows
print(df.head())

df = pd.read_csv("products.csv", encoding="utf-8-sig")
df["Price"] = df["Price"].str.replace("Â", "")  # Remove unwanted "Â" character

print(df.head())

# Read the CSV file (already downloaded, but we will clean and save it again)
df = pd.read_csv("products.csv", encoding="utf-8-sig")

# Remove the "Â" or any unwanted characters before "£"
df["Price"] = df["Price"].str.replace(r"[^\d£.]", "", regex=True)

# Save the cleaned data back to CSV
df.to_csv("products_cleaned.csv", index=False, encoding="utf-8-sig")

print("Cleaned data saved successfully! You can now download 'products_cleaned.csv'.")

from google.colab import files
files.download("products_cleaned.csv")

